/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import dao.AsignacionDAO;
import dao.SolicitudDao;
import dao.VehiculoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import modelo.Vehiculo;

public class FrmAsignacionVehiculos extends javax.swing.JInternalFrame {

     private Usuario usuarioLogueado;
    /**
     * Creates new form FrmAsignacionVehiculos
     */
    public FrmAsignacionVehiculos(Usuario usr) {
    initComponents();
    this.usuarioLogueado = usr;

    cargarSolicitudes();
}
    
        private void cargarSolicitudes() {

    SolicitudDao dao = new SolicitudDao();
    List<Object[]> lista = dao.listarTodas();

    DefaultTableModel modelo = (DefaultTableModel) tblSolicitudes.getModel();
    modelo.setRowCount(0);

    for (Object[] fila : lista) {

        String estado = fila[7].toString();

 
        if (estado.equals("APROBADA")) {

            modelo.addRow(new Object[]{
                fila[0], // id
                fila[1], // empleado
                fila[2], // destino
                fila[4], // pasajeros
                fila[5], // salida
                fila[6], // regreso
                fila[7]  // estado
            });
        }
    }
}
    
private void cargarVehiculosDisponibles() {

    int fila = tblSolicitudes.getSelectedRow();

    if (fila == -1) return;
    
    System.out.println("Pasajeros: " + tblSolicitudes.getValueAt(fila, 3));
    System.out.println("Salida: " + tblSolicitudes.getValueAt(fila, 4));
    System.out.println("Regreso: " + tblSolicitudes.getValueAt(fila, 5));

    try {

        int pasajeros = Integer.parseInt(tblSolicitudes.getValueAt(fila, 3).toString());

        java.sql.Date salida = java.sql.Date.valueOf(tblSolicitudes.getValueAt(fila, 4).toString());
        java.sql.Date regreso = java.sql.Date.valueOf(tblSolicitudes.getValueAt(fila, 5).toString());

        VehiculoDAO dao = new VehiculoDAO();
    List<Vehiculo> lista = dao.listar(); 

        DefaultTableModel modelo = (DefaultTableModel) tblVehiculos.getModel();
        modelo.setRowCount(0);

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay vehículos disponibles");
            return;
        }

        for (Vehiculo v : lista) {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getMarca(),
                v.getModelo(),
                v.getPlaca(),
                v.getPasajeros(),
                v.getTipo()
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace(); // 👈 IMPORTANTE para ver el error real
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        btnAsignar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Modelo", "Placa", "Pasajero", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tblVehiculos);

        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Empleado", "Destino", "Pasajeros", "Salida", "Regreso", "Estado"
            }
        ));
        tblSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSolicitudes);

        btnAsignar.setText("Asignar Vehículo");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnAsignar)
                        .addGap(0, 241, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
  int filaSolicitud = tblSolicitudes.getSelectedRow();
        int filaVehiculo = tblVehiculos.getSelectedRow();

        if (filaSolicitud == -1 || filaVehiculo == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione solicitud y vehículo");
            return;
        }

        try {

            int idSolicitud = (int) tblSolicitudes.getValueAt(filaSolicitud, 0);
            int idVehiculo = (int) tblVehiculos.getValueAt(filaVehiculo, 0);

            int idUsuario = usuarioLogueado.getIdUsuario();

            AsignacionDAO dao = new AsignacionDAO();

            boolean ok = dao.asignarVehiculo(idSolicitud, idVehiculo, idUsuario);

            if (ok) {
                JOptionPane.showMessageDialog(null, "Asignación realizada");

                cargarSolicitudes();
                ((DefaultTableModel) tblVehiculos.getModel()).setRowCount(0);

            } else {
                JOptionPane.showMessageDialog(null, "Auto no disponible en ese rango de fecha");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void tblSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSolicitudesMouseClicked
     cargarVehiculosDisponibles();
    }//GEN-LAST:event_tblSolicitudesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSolicitudes;
    private javax.swing.JTable tblVehiculos;
    // End of variables declaration//GEN-END:variables
}
