package vistas;

import dao.UsuarioDAO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Usuario;
import util.HashUtil;

public class FrmCambiarPassword extends javax.swing.JInternalFrame {
 private Usuario userSesion;
    /**
     * Creates new form FrmCambiarPassword
     */

    public FrmCambiarPassword(Usuario usr) {
        initComponents();
        this.userSesion = usr;
   
        txtPassword.setEchoChar('*');
        txtConfirmar.setEchoChar('*');
        
        this.setClosable(false);
        this.setIconifiable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent e) {
                cargarLogo();
            }
        });
    }
    
     private void cargarLogo(){
        ImageIcon icono = new ImageIcon(
            new ImageIcon(getClass().getResource("/img/logo.png"))
            .getImage()
            .getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), 0)
        );
        lblLogo.setIcon(icono);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtConfirmar = new javax.swing.JPasswordField();
        chkMostrarPassword = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblLogo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        btnGuardar.setBackground(new java.awt.Color(30, 30, 30));
        btnGuardar.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnGuardar.setForeground(java.awt.Color.white);
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Cambiar Contraseña");

        txtConfirmar.addActionListener(this::txtConfirmarActionPerformed);

        chkMostrarPassword.setText("Mostrar Contraseña");
        chkMostrarPassword.addActionListener(this::chkMostrarPasswordActionPerformed);

        jLabel2.setText("Contraseña nueva");

        jLabel3.setText("Confirmar contraseña");

        lblLogo.setPreferredSize(new java.awt.Dimension(120, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnGuardar)
                        .addGap(24, 24, 24)
                        .addComponent(chkMostrarPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(chkMostrarPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String pass1 = txtPassword.getText();
        String pass2 = txtConfirmar.getText();

        if (pass1.isEmpty() || pass2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }

        if (!pass1.equals(pass2)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
            return;
        }

        // actualizar en BD
        UsuarioDAO dao = new UsuarioDAO();
                
        String nuevaHash = HashUtil.sha256(pass1).toUpperCase();
        String actualHash = dao.obtenerPasswordActual(userSesion.getIdUsuario());
        
        // comparar
        if (nuevaHash.equals(actualHash)) {
            JOptionPane.showMessageDialog(this, 
                "La nueva contraseña no puede ser igual a la anterior");
            return;
        }

        boolean ok = dao.cambiarPassword(userSesion.getIdUsuario(), pass1);
        
        if (ok) {
            JOptionPane.showMessageDialog(this, "Contraseña actualizada");
            userSesion.setDebeCambiarPassword(false); 
            this.dispose(); // cerrar ventana

        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarActionPerformed
        btnGuardar.doClick();
    }//GEN-LAST:event_txtConfirmarActionPerformed

    private void chkMostrarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarPasswordActionPerformed

        if (chkMostrarPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0);
            txtConfirmar.setEchoChar((char) 0);
        } else {
            txtConfirmar.setEchoChar('•');
            txtPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_chkMostrarPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkMostrarPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
