package vistas;

import dao.EmpleadoDAO;
import java.text.ParseException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelo.Empleado;

public class FrmEmpleados extends javax.swing.JInternalFrame {
    EmpleadoDAO dao = new EmpleadoDAO();
    /**
     * Creates new form FrmEmpleados
     */
    public FrmEmpleados() {
        initComponents();
        cargarTabla();
        formatoDui();
        formatoTelefono();
        ButtonGroup grupoLicencia = new ButtonGroup();
        grupoLicencia.add(rbSiLicencia);
        grupoLicencia.add(rbNoLicencia);
        
        rbNoLicencia.setSelected(true);
        cmbLicencia.setEnabled(false);
        cmbLicencia.setSelectedItem("SIN LICENCIA");
        btnGuardar.setEnabled(true);
        btnActualizar.setEnabled(false);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDui = new javax.swing.JFormattedTextField();
        txtCargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        rbSiLicencia = new javax.swing.JRadioButton();
        rbNoLicencia = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnLimpiar1 = new javax.swing.JButton();
        cmbLicencia = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setText("REGISTROS DE EMPLEADOS");

        jLabel1.setText("Nombres:");

        jLabel2.setText("Apellidos:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("DUI:");

        try {
            txtDui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Cargo:");

        jLabel6.setText("Departamento:");

        jLabel8.setText("¿Posee Licencia?");

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Dui", "Telefono", "Cargo", "Departamento", "Estado", "Licencia", "Usuario"
            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        rbSiLicencia.setText("Si");
        rbSiLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSiLicenciaActionPerformed(evt);
            }
        });

        rbNoLicencia.setText("No");
        rbNoLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoLicenciaActionPerformed(evt);
            }
        });

        jLabel10.setText("Licencia:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtIdEmpleado.setEditable(false);
        txtIdEmpleado.setEnabled(false);

        jLabel11.setText("Id:");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel7.setText("Buscar por Apellidos: ");

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        cmbLicencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIN LICENCIA", "PARTICULAR", "LIVIANA", "PESADA" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbLicencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDui))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(rbSiLicencia)
                                .addGap(18, 18, 18)
                                .addComponent(rbNoLicencia)))
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(btnGuardar)
                        .addGap(30, 30, 30)
                        .addComponent(btnActualizar)
                        .addGap(36, 36, 36)
                        .addComponent(btnLimpiar1)))
                .addGap(0, 262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(rbSiLicencia)
                            .addComponent(rbNoLicencia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnLimpiar1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblEmpleados.getModel();
        modelo.setRowCount(0);

        for (Empleado e : dao.listar()) {
            modelo.addRow(new Object[]{
                e.getIdEmpleado(),
                e.getNombres(),
                e.getApellidos(),
                e.getDui(),
                e.getTelefono(),
                e.getCargo(),
                e.getDepartamento(),
                e.getEstado(),
                e.getLicencia(),
                e.getUsername()
            });
        }
    }
    
    private void formatoDui() {
        try {
            MaskFormatter formatter = new MaskFormatter("########-#");
            formatter.setPlaceholderCharacter('_');
            txtDui.setFormatterFactory(new DefaultFormatterFactory(formatter));
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }
    
    private void formatoTelefono() {

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {

            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {

                char c = evt.getKeyChar();

                // permitir backspace
                if (c == '\b') {
                    return;
                }

                // SOLO NUMEROS
                if (!Character.isDigit(c)) {
                    evt.consume();
                    return;
                }

                String texto = txtTelefono.getText()
                        .replace("-", "");

                // MAXIMO 8 DIGITOS
                if (texto.length() >= 8) {
                    evt.consume();
                }
            }

            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {

                String telefono = txtTelefono.getText()
                        .replace("-", "");

                // ELIMINAR TODO LO QUE NO SEA NUMERO
                telefono = telefono.replaceAll("[^0-9]", "");

                // MAXIMO 8 DIGITOS
                if (telefono.length() > 8) {
                    telefono = telefono.substring(0, 8);
                }

                // INSERTAR GUION AUTOMATICO
                if (telefono.length() > 4) {

                    telefono =
                            telefono.substring(0, 4)
                            + "-"
                            + telefono.substring(4);
                }

                txtTelefono.setText(telefono);

                // CURSOR AL FINAL
                txtTelefono.setCaretPosition(
                        txtTelefono.getText().length()
                );
            }
        });
    }
    
    private void validarSoloLetras(String texto, String campo) throws Exception {

        if (!texto.trim().matches("[a-zA-ZÁÉÍÓÚáéíóúÑñ ]+")) {

            throw new Exception(
                    "El campo " + campo + " solo debe contener letras."
            );
        }
    }
    
    private void validarCampos() throws Exception {
        if (txtNombres.getText().trim().isEmpty() ||
            txtApellidos.getText().trim().isEmpty() ||
            txtCargo.getText().trim().isEmpty() ||
            txtDepartamento.getText().trim().isEmpty()) {

            throw new Exception("Todos los campos deben completarse.");
        }
        
        validarSoloLetras(txtNombres.getText(), "Nombres");
        validarSoloLetras(txtApellidos.getText(), "Apellidos");
        validarSoloLetras(txtCargo.getText(), "Cargo");
        validarSoloLetras(txtDepartamento.getText(), "Departamento");

        if (txtDui.getText().contains("_")) {
            throw new Exception("Complete el DUI.");
        }
        
        String telefono = txtTelefono.getText().replace("-", "");

        if (!(telefono.startsWith("7") || telefono.startsWith("6")
                || telefono.startsWith("2"))) {
            throw new Exception("El teléfono debe iniciar con 2, 6 o 7");
        }

        if (telefono.length() != 8) {
            throw new Exception("El teléfono debe tener 8 dígitos.");
        }
    }
    
    public void limpiar() {
        txtIdEmpleado.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCargo.setText("");
        txtDepartamento.setText("");
        txtDui.setText("");
        txtTelefono.setText("");
        
        rbNoLicencia.setSelected(true);
        cmbLicencia.setEnabled(false);
        cmbLicencia.setSelectedItem("SIN LICENCIA");

        
        btnGuardar.setEnabled(true);
        btnActualizar.setEnabled(false);
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        try {
            validarCampos();

            String dui = txtDui.getText();

            if (dao.duiExiste(0, dui)) {
                throw new Exception("DUI ya existe.");
            }
            
            String licencia = cmbLicencia.getSelectedItem().toString();

            if (rbSiLicencia.isSelected() && "SIN LICENCIA".equals(licencia)) {
                throw new Exception("Debe seleccionar un tipo de licencia.");
            }

            if (rbNoLicencia.isSelected()) {
                licencia = "SIN LICENCIA";
            }

            Empleado e = new Empleado();

            e.setNombres(txtNombres.getText());
            e.setApellidos(txtApellidos.getText());
            e.setDui(dui);
            e.setTelefono(txtTelefono.getText());
            e.setCargo(txtCargo.getText());
            e.setDepartamento(txtDepartamento.getText());
            e.setLicencia(licencia);

            if (dao.insertar(e)) {
                JOptionPane.showMessageDialog(this, "Guardado");
                cargarTabla();
                limpiar();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        int fila = tblEmpleados.getSelectedRow();

        if (fila == -1) return;
       

        txtIdEmpleado.setText(tblEmpleados.getValueAt(fila, 0).toString());
        txtNombres.setText(tblEmpleados.getValueAt(fila, 1).toString());
        txtApellidos.setText(tblEmpleados.getValueAt(fila, 2).toString());
        txtDui.setText(tblEmpleados.getValueAt(fila, 3).toString());
        txtTelefono.setText(tblEmpleados.getValueAt(fila, 4).toString());
        txtCargo.setText(tblEmpleados.getValueAt(fila, 5).toString());
        txtDepartamento.setText(tblEmpleados.getValueAt(fila, 6).toString());

        String lic = tblEmpleados.getValueAt(fila, 8).toString();

        // Licencia
        if ("SIN LICENCIA".equals(lic)) {
            rbNoLicencia.setSelected(true);
            cmbLicencia.setEnabled(false);
            cmbLicencia.setSelectedItem("SIN LICENCIA");
        } else {
            rbSiLicencia.setSelected(true);
            cmbLicencia.setEnabled(true);
            cmbLicencia.setSelectedItem(lic);
        }

        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(true);
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            validarCampos();

            int id = Integer.parseInt(txtIdEmpleado.getText());
            String dui = txtDui.getText();

            if (dao.duiExiste(id, dui)) {
                throw new Exception("DUI ya existe.");
            }
            
            String licencia = cmbLicencia.getSelectedItem().toString();

            if (rbSiLicencia.isSelected() && "SIN LICENCIA".equals(licencia)) {
                throw new Exception("Debe seleccionar un tipo de licencia.");
            }

            if (rbNoLicencia.isSelected()) {
                licencia = "SIN LICENCIA";
            }

            Empleado e = new Empleado();

            e.setIdEmpleado(id);
            e.setNombres(txtNombres.getText());
            e.setApellidos(txtApellidos.getText());
            e.setDui(dui);
            e.setTelefono(txtTelefono.getText());
            e.setCargo(txtCargo.getText());
            e.setDepartamento(txtDepartamento.getText());
            e.setLicencia(licencia);

            if (dao.actualizar(e)) {
                JOptionPane.showMessageDialog(this, "Actualizado correctamente");
                cargarTabla();
                limpiar();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void rbSiLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSiLicenciaActionPerformed
        cmbLicencia.setEnabled(true);

        // evitar que quede en SIN LICENCIA
        if ("SIN LICENCIA".equals(cmbLicencia.getSelectedItem())) {
            cmbLicencia.setSelectedItem("PARTICULAR");
        }
    }//GEN-LAST:event_rbSiLicenciaActionPerformed

    private void rbNoLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoLicenciaActionPerformed
        cmbLicencia.setEnabled(false);
        cmbLicencia.setSelectedItem("SIN LICENCIA");
    }//GEN-LAST:event_rbNoLicenciaActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        int pos = txtBuscar.getCaretPosition();

        txtBuscar.setText(txtBuscar.getText().toUpperCase());
        txtBuscar.setCaretPosition(pos);

        String apellidos = txtBuscar.getText();

        DefaultTableModel modelo = (DefaultTableModel) tblEmpleados.getModel();
        modelo.setRowCount(0);

        if (apellidos.isEmpty()) {
            cargarTabla();
            return;
        }

        for (Empleado e : dao.buscarPorApellidos(apellidos)) {
            modelo.addRow(new Object[]{
                e.getIdEmpleado(),
                e.getNombres(),
                e.getApellidos(),
                e.getDui(),
                e.getTelefono(),
                e.getCargo(),
                e.getDepartamento(),
                e.getEstado(),
                e.getLicencia(),
                e.getUsername()
            });
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JComboBox<String> cmbLicencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbNoLicencia;
    private javax.swing.JRadioButton rbSiLicencia;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JFormattedTextField txtDui;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
