package vistas;

import modelo.Usuario;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());
    
     private Usuario userSesion;

    public FrmPrincipal() {
        initComponents();
        configurarVentana();
    }

    public FrmPrincipal(Usuario usr) {
        initComponents();
        this.userSesion = usr;
        configurarVentana();
        mostrarMensajeUsuario();
        mostrarUsuarioMenu();
        validarCambioPassword();
        aplicarRoles(); 

    }

    private void configurarVentana() {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    private void mostrarMensajeUsuario() {
        if (userSesion != null) {
            this.setTitle("SGV - Sistema de Gestión Vehicular | " + userSesion.getUsername().toUpperCase());
        }
    }
    
    private void mostrarUsuarioMenu() {
        if (userSesion != null) {
            menuUsuario.setText(userSesion.getUsername());
        } else {
            menuUsuario.setText("Usuario");
        }
    }

    private void abrirFormulario(JInternalFrame frm) {
        for (JInternalFrame frame : escritorio.getAllFrames()) {
            if (frame.getClass().equals(frm.getClass())) {
                frame.toFront();
                frame.requestFocus();
                return;
            }
        }

        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
    }
    
    private void validarCambioPassword() {
        if (userSesion != null && userSesion.isDebeCambiarPassword()){

            JOptionPane.showMessageDialog(
                this,
                "Debe cambiar su contraseña antes de continuar",
                "Cambio obligatorio",
                JOptionPane.WARNING_MESSAGE
            );

            FrmCambiarPassword frm = new FrmCambiarPassword(userSesion);
            abrirFormulario(frm);
        }
    }
    
        private void aplicarRoles() {

        if (userSesion == null) return;

        String rol = userSesion.getRol();


        if (rol.equalsIgnoreCase("ADMIN")) {
            mItemUsuarios.setVisible(true);
            mItemEmpleados.setVisible(true);
            mItemVehiculos.setVisible(true);
            mItemSolicitudes.setVisible(true);
            mItemAsignaciones.setVisible(true);
            mItemReportes.setVisible(true);
        }


        else if (rol.equalsIgnoreCase("ENCARGADO")) {
            mItemUsuarios.setVisible(false); // no administra usuarios
            mItemEmpleados.setVisible(false);

            mItemVehiculos.setVisible(true);
            mItemSolicitudes.setVisible(true);
            mItemAsignaciones.setVisible(true);
            mItemReportes.setVisible(false);
        }


        else if (rol.equalsIgnoreCase("EMPLEADO")) {
            mItemUsuarios.setVisible(false);
            mItemEmpleados.setVisible(false);
            mItemVehiculos.setVisible(false);
            mItemAsignaciones.setVisible(false);
            mItemReportes.setVisible(false);

            mItemSolicitudes.setVisible(true); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        mItemSesion = new javax.swing.JMenuItem();
        menuModulo = new javax.swing.JMenu();
        mItemUsuarios = new javax.swing.JMenuItem();
        mItemEmpleados = new javax.swing.JMenuItem();
        mItemVehiculos = new javax.swing.JMenuItem();
        mItemSolicitudes = new javax.swing.JMenuItem();
        mItemAsignaciones = new javax.swing.JMenuItem();
        mItemReportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        menuUsuario.setText("Usuario");

        mItemSesion.setText("Cerrar Sesión");
        mItemSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSesionActionPerformed(evt);
            }
        });
        menuUsuario.add(mItemSesion);

        jMenuBar1.add(menuUsuario);

        menuModulo.setText("Modulos");
        menuModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModuloActionPerformed(evt);
            }
        });

        mItemUsuarios.setText("Usuarios");
        mItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemUsuariosActionPerformed(evt);
            }
        });
        menuModulo.add(mItemUsuarios);

        mItemEmpleados.setText("Empleados");
        mItemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemEmpleadosActionPerformed(evt);
            }
        });
        menuModulo.add(mItemEmpleados);

        mItemVehiculos.setText("Vehiculos");
        mItemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemVehiculosActionPerformed(evt);
            }
        });
        menuModulo.add(mItemVehiculos);

        mItemSolicitudes.setText("Solicitudes");
        menuModulo.add(mItemSolicitudes);

        mItemAsignaciones.setText("Asignaciones");
        mItemAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAsignacionesActionPerformed(evt);
            }
        });
        menuModulo.add(mItemAsignaciones);

        mItemReportes.setText("Reportes");
        menuModulo.add(mItemReportes);

        jMenuBar1.add(menuModulo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuModuloActionPerformed

    private void mItemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemVehiculosActionPerformed
        abrirFormulario(new FrmVehiculos());
    }//GEN-LAST:event_mItemVehiculosActionPerformed

    private void mItemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemEmpleadosActionPerformed
       abrirFormulario(new FrmEmpleados());
    }//GEN-LAST:event_mItemEmpleadosActionPerformed

    private void mItemSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSesionActionPerformed
        String nombre = userSesion != null ? userSesion.getUsername() : "Usuario";

        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que desea cerrar sesión, " + nombre + "?",
            "Cerrar sesión",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            new FrmLogin().setVisible(true);
        }
    }//GEN-LAST:event_mItemSesionActionPerformed

    private void mItemAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAsignacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemAsignacionesActionPerformed

    private void mItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemUsuariosActionPerformed
       abrirFormulario(new FrmUsuarios());
    }//GEN-LAST:event_mItemUsuariosActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemAsignaciones;
    private javax.swing.JMenuItem mItemEmpleados;
    private javax.swing.JMenuItem mItemReportes;
    private javax.swing.JMenuItem mItemSesion;
    private javax.swing.JMenuItem mItemSolicitudes;
    private javax.swing.JMenuItem mItemUsuarios;
    private javax.swing.JMenuItem mItemVehiculos;
    private javax.swing.JMenu menuModulo;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
