package vistas;

import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import dao.SolicitudDao;
import javax.swing.JOptionPane;
import modelo.Solicitud;

public class FrmSolicitudesEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmSolicitudesEmpleado
     */
    
    private Usuario usuario;
    private int idEmpleado;
    private SolicitudDao dao = new SolicitudDao();
    private Solicitud s = new Solicitud();


    public FrmSolicitudesEmpleado(Usuario usr) {
        initComponents();
        
        this.usuario = usr;

        dcSalida.setDateFormatString("yyyy-MM-dd");
        dcRegreso.setDateFormatString("yyyy-MM-dd");

        validarRol();
        cargarTabla();
    }
    
    private void validarRol() {

        if (!usuario.getRol().equalsIgnoreCase("EMPLEADO")) {
            JOptionPane.showMessageDialog(this, 
                "No tiene permisos para acceder a este módulo");

            this.dispose(); // cierra el form
        }
    }

    
    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblSolicitudes.getModel();
        modelo.setRowCount(0);

        for (Object[] fila : dao.listarPorEmpleado(usuario.getIdEmpleado())) {
            modelo.addRow(fila);
        }
    }
    
    private void validarCampos() throws Exception {

        if (txtDestino.getText().trim().isEmpty() ||
            txtMotivo.getText().trim().isEmpty() ||
            txtPasajeros.getText().trim().isEmpty()) {

            throw new Exception("Todos los campos deben completarse");
        }

        if (dcSalida.getDate() == null || dcRegreso.getDate() == null) {
            throw new Exception("Debe seleccionar las fechas");
        }

        if (dcRegreso.getDate().before(dcSalida.getDate())) {
            throw new Exception("La fecha de regreso no puede ser menor");
        }

        try {
            int pasajeros = Integer.parseInt(txtPasajeros.getText());
            if (pasajeros <= 0) {
                throw new Exception("Pasajeros debe ser mayor a 0");
            }
        } catch (NumberFormatException e) {
            throw new Exception("Pasajeros debe ser numérico");
        }
    }
    
    private void limpiar() {
        txtDestino.setText("");
        txtMotivo.setText("");
        txtPasajeros.setText("");
        dcSalida.setDate(null);
        dcRegreso.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        lblMaterias = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPasajeros = new javax.swing.JFormattedTextField();
        txtDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dcSalida = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        dcRegreso = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("SOLICITUDES DE EMPLEADO");

        jLabel2.setText("Destino: ");

        txtMotivo.setColumns(20);
        txtMotivo.setRows(5);
        txtMotivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtMotivo);

        lblMaterias.setText("Motivo:");

        jLabel3.setText("Pasajeros:");

        txtPasajeros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel4.setText("Fecha de salida:");

        jLabel5.setText("Fecha de Regreso:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar Solicitud");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Destino", "Motivo", "Pasajeros", "Salida", "Regreso", "Estado"
            }
        ));
        tblSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSolicitudes);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtDestino))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dcSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dcRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMaterias)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dcSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(dcRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblMaterias))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar)
                            .addComponent(btnActualizar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         try {
            validarCampos();

            s.setIdEmpleado(usuario.getIdEmpleado());
            s.setDestino(txtDestino.getText().trim());
            s.setMotivoViaje(txtMotivo.getText().trim());
            s.setPasajeros(Integer.parseInt(txtPasajeros.getText()));

            java.sql.Date salida = new java.sql.Date(dcSalida.getDate().getTime());
            java.sql.Date regreso = new java.sql.Date(dcRegreso.getDate().getTime());

            s.setFechaSalida(salida);
            s.setFechaRegreso(regreso);

            if (dao.insertar(s)) {
                JOptionPane.showMessageDialog(this, "Solicitud creada");
                cargarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private int obtenerIdSeleccionado() {
        int fila = tblSolicitudes.getSelectedRow();
        
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una solicitud de la tabla");
            return -1;
        }
        
        String estado = tblSolicitudes.getValueAt(fila, 6).toString();
        
        if (!estado.equalsIgnoreCase("PENDIENTE")) {
            JOptionPane.showMessageDialog(this, 
                "Solo se pueden actualizar/cancelar solicitudes pendientes");
            return -1;
        }

        return Integer.parseInt(tblSolicitudes.getValueAt(fila, 0).toString());
    }
    
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int id = obtenerIdSeleccionado();
        if (id == -1) return;

        String motivo = JOptionPane.showInputDialog(this,
                "Ingrese el motivo de cancelación:");

        if (motivo == null) return;

        if (motivo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar un motivo");
            return;
        }

        if (dao.cancelar(id, usuario.getIdEmpleado(), motivo)) {
            JOptionPane.showMessageDialog(this, "Solicitud cancelada");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo cancelar");
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int id = obtenerIdSeleccionado();
        if (id == -1) return;

        try {
            validarCampos();

            s.setId(id);
            s.setIdEmpleado(usuario.getIdEmpleado());
            s.setDestino(txtDestino.getText().trim());
            s.setMotivoViaje(txtMotivo.getText().trim());
            s.setPasajeros(Integer.parseInt(txtPasajeros.getText()));

            s.setFechaSalida(new java.sql.Date(dcSalida.getDate().getTime()));
            s.setFechaRegreso(new java.sql.Date(dcRegreso.getDate().getTime()));

            if (dao.actualizar(s)) {
                JOptionPane.showMessageDialog(this, "Solicitud actualizada");
                cargarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSolicitudesMouseClicked
        int fila = tblSolicitudes.getSelectedRow();

        txtDestino.setText(tblSolicitudes.getValueAt(fila, 1).toString());
        txtMotivo.setText(tblSolicitudes.getValueAt(fila, 2).toString());
        txtPasajeros.setText(tblSolicitudes.getValueAt(fila, 3).toString());

        dcSalida.setDate((java.util.Date) tblSolicitudes.getValueAt(fila, 4));
        dcRegreso.setDate((java.util.Date) tblSolicitudes.getValueAt(fila, 5));
    }//GEN-LAST:event_tblSolicitudesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dcRegreso;
    private com.toedter.calendar.JDateChooser dcSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaterias;
    private javax.swing.JTable tblSolicitudes;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JFormattedTextField txtPasajeros;
    // End of variables declaration//GEN-END:variables
}
