package vistas;

import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import dao.SolicitudDao;
import javax.swing.JOptionPane;
import modelo.Solicitud;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableCellRenderer;

public class FrmSolicitudesEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmSolicitudesEmpleado
     */
    
    private Usuario usuario;
    private int idEmpleado;
    private SolicitudDao dao = new SolicitudDao();
    private Solicitud s = new Solicitud();
    java.util.Date hoySinHora = quitarHora(new java.util.Date());


    public FrmSolicitudesEmpleado(Usuario usr) {
        initComponents();
        
        this.usuario = usr;
        lblIdConductor.setText("");
        validarRol();

        dcSalida.setDateFormatString("dd/MM/yyyy");
        dcRegreso.setDateFormatString("dd/MM/yyyy");
        dcSalida.setMinSelectableDate(hoySinHora);
        dcRegreso.setMinSelectableDate(hoySinHora);
        
        txtConductor.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        //validar si el empleado tiene licencia y setear la info
        configurarConductor();
       
        cargarTabla();
    }
    
    private void validarRol() {

        if (!usuario.getRol().equalsIgnoreCase("EMPLEADO")) {
            JOptionPane.showMessageDialog(this, 
                "No tiene permisos para acceder a este módulo");
            this.dispose(); // cierra el form
        }
    }
    
    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblSolicitudes.getModel();
        modelo.setRowCount(0);

        for (Object[] fila : dao.listarPorEmpleado(usuario.getIdEmpleado())) {
            modelo.addRow(fila);
        }
    }
    
    //para validar que la fecha de salida sea hoy, pero sin hora porque da error
    private java.util.Date quitarHora(java.util.Date fecha) {
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(fecha);
        cal.set(java.util.Calendar.HOUR_OF_DAY, 0);
        cal.set(java.util.Calendar.MINUTE, 0);
        cal.set(java.util.Calendar.SECOND, 0);
        cal.set(java.util.Calendar.MILLISECOND, 0);
        return cal.getTime();
    }
    
    private void validarCampos() throws Exception {

        if (txtDestino.getText().trim().isEmpty() ||
            txtMotivo.getText().trim().isEmpty() ||
            txtPasajeros.getText().trim().isEmpty()) {

            throw new Exception("Todos los campos deben completarse");
        }
        
        java.util.Date hoySinHora = quitarHora(new java.util.Date());
        
        if (dcSalida.getDate() == null || dcRegreso.getDate() == null) {
            throw new Exception("Debe seleccionar las fechas");
        }

        java.util.Date salida = quitarHora(dcSalida.getDate());
        java.util.Date regreso = quitarHora(dcRegreso.getDate());
        
        if (salida.before(hoySinHora)) {
            throw new Exception("La fecha de salida no puede ser anterior a hoy");
        }

        if (regreso.before(salida)) {
            throw new Exception("La fecha de regreso no puede ser anterior a la de salida");
        }

        try {
            int pasajeros = Integer.parseInt(txtPasajeros.getText());
            if (pasajeros <= 0) {
                throw new Exception("Pasajeros debe ser mayor a 0");
            }
        } catch (NumberFormatException e) {
            throw new Exception("Pasajeros debe ser numérico");
        }
    }
    
    private void limpiar() {
        txtDestino.setText("");
        txtMotivo.setText("");
        txtPasajeros.setText("");
        dcSalida.setDate(null);
        dcRegreso.setDate(null);

        btnGuardar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        configurarConductor();
    }
    
    private void configurarConductor() {

        lblIdConductor.setText("");
        txtConductor.setText("");

        if (dao.empleadoTieneLicencia(usuario.getIdEmpleado())) {

            lblIdConductor.setText(String.valueOf(usuario.getIdEmpleado()));

            String nombre = dao.obtenerNombreEmpleado(usuario.getIdEmpleado());
            txtConductor.setText(nombre);

            btnBuscar.setEnabled(false);

        } else {
            btnBuscar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        lblMaterias = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPasajeros = new javax.swing.JFormattedTextField();
        txtDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblMaterias1 = new javax.swing.JLabel();
        txtConductor = new javax.swing.JTextField();
        lblIdConductor = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        dcSalida = new com.toedter.calendar.JDateChooser();
        dcRegreso = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("SOLICITUDES DE EMPLEADO");

        jLabel2.setText("Destino: ");

        txtMotivo.setColumns(20);
        txtMotivo.setRows(5);
        txtMotivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtMotivo);

        lblMaterias.setText("Motivo:");

        jLabel3.setText("Pasajeros:");

        txtPasajeros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel4.setText("Fecha de salida:");

        jLabel5.setText("Fecha de Regreso:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar ");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Destino", "Motivo", "Pasajeros", "Salida", "Regreso", "Estado", "Id Conductor", "Conductor"
            }
        ));
        tblSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSolicitudes);
        if (tblSolicitudes.getColumnModel().getColumnCount() > 0) {
            tblSolicitudes.getColumnModel().getColumn(7).setResizable(false);
            tblSolicitudes.getColumnModel().getColumn(8).setResizable(false);
        }

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblMaterias1.setText("Conductor:");

        lblIdConductor.setText("jLabel6");
        lblIdConductor.setToolTipText("");
        lblIdConductor.setEnabled(false);
        lblIdConductor.setFocusable(false);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        dcSalida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcSalidaPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblMaterias)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnGuardar)
                        .addGap(23, 23, 23)
                        .addComponent(btnActualizar)
                        .addGap(32, 32, 32)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblMaterias1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(txtConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(lblIdConductor))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(346, 346, 346))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37))
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(dcSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCancelar)
                                    .addComponent(btnLimpiar)
                                    .addComponent(btnGuardar)
                                    .addComponent(btnActualizar))
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(lblMaterias)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaterias1)
                            .addComponent(txtConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdConductor))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      try {
        validarCampos();

        int idConductor;

        if (dao.empleadoTieneLicencia(usuario.getIdEmpleado())) {
            idConductor = usuario.getIdEmpleado();
        } else {

            if (lblIdConductor.getText().isEmpty()) {
                throw new Exception("Debe seleccionar un conductor");
            }

            idConductor = Integer.parseInt(lblIdConductor.getText());
        }


        java.sql.Date salida = new java.sql.Date(dcSalida.getDate().getTime());
        java.sql.Date regreso = new java.sql.Date(dcRegreso.getDate().getTime());

        if (!dao.empleadoDisponible(usuario.getIdEmpleado(), salida, regreso, 0)) {
            throw new Exception("Ya tiene una solicitud registrada en esas fechas");
        }
        if (!dao.conductorDisponible(idConductor, salida, regreso, 0)) {
            throw new Exception("El conductor no está disponible en esas fechas");
        }

        s.setIdEmpleado(usuario.getIdEmpleado());
        s.setIdConductor(idConductor);
        s.setDestino(txtDestino.getText().trim());
        s.setMotivoViaje(txtMotivo.getText().trim());
        s.setPasajeros(Integer.parseInt(txtPasajeros.getText()));

        s.setFechaSalida(salida);
        s.setFechaRegreso(regreso);

        if (dao.insertar(s)) {
            JOptionPane.showMessageDialog(this, "Solicitud creada correctamente");
            cargarTabla();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private int obtenerIdSeleccionado() {
        int fila = tblSolicitudes.getSelectedRow();
        
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una solicitud de la tabla");
            return -1;
        }
        
        String estado = tblSolicitudes.getValueAt(fila, 6).toString();
        
        if (!estado.equalsIgnoreCase("PENDIENTE")) {
            JOptionPane.showMessageDialog(this, 
                "Solo se pueden actualizar/cancelar solicitudes pendientes");
            return -1;
        }

        return Integer.parseInt(tblSolicitudes.getValueAt(fila, 0).toString());
    }
    
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int id = obtenerIdSeleccionado();
        if (id == -1) return;

        String motivo = JOptionPane.showInputDialog(this,
                "Ingrese el motivo de cancelación:");

        if (motivo == null) return;

        if (motivo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar un motivo");
            return;
        }

        if (dao.cancelar(id, usuario.getIdEmpleado(), motivo)) {
            JOptionPane.showMessageDialog(this, "Solicitud cancelada");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo cancelar");
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int id = obtenerIdSeleccionado();
        if (id == -1) return;

        try {
            validarCampos();

            int idConductor;

            if (dao.empleadoTieneLicencia(usuario.getIdEmpleado())) {
                idConductor = usuario.getIdEmpleado();
            } else {
                if (lblIdConductor.getText().isEmpty()) {
                    throw new Exception("Debe seleccionar un conductor");
                }
                idConductor = Integer.parseInt(lblIdConductor.getText());
            }


            java.sql.Date salida = new java.sql.Date(dcSalida.getDate().getTime());
            java.sql.Date regreso = new java.sql.Date(dcRegreso.getDate().getTime());

            if (!dao.empleadoDisponible(usuario.getIdEmpleado(), salida, regreso, id)) {
                throw new Exception("Ya tiene una solicitud registrada en esas fechas");
            }
            if (!dao.conductorDisponible(idConductor, salida, regreso, id)) {
                throw new Exception("El conductor no está disponible en esas fechas");
            }

            s.setId(id);
            s.setIdEmpleado(usuario.getIdEmpleado());
            s.setIdConductor(idConductor);
            s.setDestino(txtDestino.getText().trim());
            s.setMotivoViaje(txtMotivo.getText().trim());
            s.setPasajeros(Integer.parseInt(txtPasajeros.getText()));

            s.setFechaSalida(salida);
            s.setFechaRegreso(regreso);

            if (dao.actualizar(s)) {
                JOptionPane.showMessageDialog(this, "Solicitud actualizada");
                cargarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        limpiar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSolicitudesMouseClicked
        int fila = tblSolicitudes.getSelectedRow();

        txtDestino.setText(tblSolicitudes.getValueAt(fila, 1).toString());
        txtMotivo.setText(tblSolicitudes.getValueAt(fila, 2).toString());
        txtPasajeros.setText(tblSolicitudes.getValueAt(fila, 3).toString());

        dcSalida.setDate((java.util.Date) tblSolicitudes.getValueAt(fila, 4));
        dcRegreso.setDate((java.util.Date) tblSolicitudes.getValueAt(fila, 5));
        String estado = tblSolicitudes.getValueAt(fila, 6).toString();
        Object idConductor = tblSolicitudes.getValueAt(fila, 7);
        Object nombreConductor = tblSolicitudes.getValueAt(fila, 8);
        
        if (idConductor != null) {
            lblIdConductor.setText(idConductor.toString());
            txtConductor.setText(nombreConductor != null ? nombreConductor.toString() : "");
        }
        
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(true);
        
        if (!estado.equalsIgnoreCase("PENDIENTE")) {
            btnBuscar.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnActualizar.setEnabled(false);
        } else {
            btnCancelar.setEnabled(true);
            btnActualizar.setEnabled(true);
            if (!dao.empleadoTieneLicencia(usuario.getIdEmpleado())) {
                btnBuscar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tblSolicitudesMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (dcSalida.getDate() == null || dcRegreso.getDate() == null) {
            JOptionPane.showMessageDialog(this,"Debe seleccionar las fechas antes de buscar conductor");
            return;
        }
        
        FrmBuscarConductor frm =
            new FrmBuscarConductor(
                null,
                true,
                dcSalida.getDate(),
                dcRegreso.getDate()
            );
        frm.setVisible(true);

        if (frm.idSeleccionado != 0) {
            lblIdConductor.setText(String.valueOf(frm.idSeleccionado));
            txtConductor.setText(frm.nombreSeleccionado);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void dcSalidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcSalidaPropertyChange
        if (!"date".equals(evt.getPropertyName())) {
            return;
        }

        java.util.Date fechaSalida = dcSalida.getDate();

        if (fechaSalida == null) {
            dcRegreso.setMinSelectableDate(hoySinHora);
            return;
        }

        if (fechaSalida.before(hoySinHora)) {

            JOptionPane.showMessageDialog(
                this,
                "La fecha de salida no puede ser anterior a hoy"
            );

            dcSalida.setDate(null);
            dcRegreso.setMinSelectableDate(hoySinHora);
            return;
        }

        // Bloquea todas las fechas anteriores a la salida
        dcRegreso.setMinSelectableDate(fechaSalida);

        // Si la fecha de regreso quedó antes de la salida, la limpia
        if (dcRegreso.getDate() != null
                && dcRegreso.getDate().before(fechaSalida)) {

            dcRegreso.setDate(null);
        }
    }//GEN-LAST:event_dcSalidaPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private com.toedter.calendar.JDateChooser dcRegreso;
    private com.toedter.calendar.JDateChooser dcSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdConductor;
    private javax.swing.JLabel lblMaterias;
    private javax.swing.JLabel lblMaterias1;
    private javax.swing.JTable tblSolicitudes;
    private javax.swing.JTextField txtConductor;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JFormattedTextField txtPasajeros;
    // End of variables declaration//GEN-END:variables
}
