package vistas;

import dao.SolicitudDao;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import modelo.Usuario;

public class FrmSolicitudesAdmin extends javax.swing.JInternalFrame {
    
    private Usuario usuario;
    private SolicitudDao dao = new SolicitudDao();
    
    public FrmSolicitudesAdmin(Usuario usr) {
        initComponents();
        this.usuario = usr;
        validarRol();
        cargarTabla();
    }
    
    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblSolicitudes.getModel();
        modelo.setRowCount(0);

        for (Object[] fila : dao.listarTodas()) {
            modelo.addRow(fila);
        }
    }
    
    private void validarRol() {
        if (!usuario.getRol().equalsIgnoreCase("ADMIN") &&
            !usuario.getRol().equalsIgnoreCase("ENCARGADO")) {

            JOptionPane.showMessageDialog(this,
                    "No tiene permisos para acceder a este módulo");
            this.dispose();
        }
    }
    
    private int obtenerIdSeleccionado() {
        int fila = tblSolicitudes.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una solicitud de la tabla");
            return -1;
        }

        String estado = tblSolicitudes.getValueAt(fila, 7).toString();

        if (!estado.equalsIgnoreCase("PENDIENTE")) {
            JOptionPane.showMessageDialog(this,
                    "Solo se pueden gestionar solicitudes pendientes");
            return -1;
        }

        return Integer.parseInt(tblSolicitudes.getValueAt(fila, 0).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        btnAprovar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Empleado", "Destino", "Motivo", "Pasajeros", "Salida", "Regreso", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblSolicitudes);

        btnAprovar.setText("Aprovar");
        btnAprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprovarActionPerformed(evt);
            }
        });

        btnRechazar.setText("Rechazar");
        btnRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechazarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("GESTIÓN DE SOLICITUDES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnAprovar)
                        .addGap(55, 55, 55)
                        .addComponent(btnRechazar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprovar)
                    .addComponent(btnRechazar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovarActionPerformed
        int id = obtenerIdSeleccionado();
        if (id == -1) return;

        String motivo = JOptionPane.showInputDialog(this,
                "Ingrese motivo de aprobación:");

        if (motivo == null || motivo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un motivo");
            return;
        }

        if (dao.aprobar(id, motivo)) {
            JOptionPane.showMessageDialog(this, "Solicitud aprobada");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al aprobar");
        }
    }//GEN-LAST:event_btnAprovarActionPerformed

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
        int id = obtenerIdSeleccionado();
        if (id == -1) return;

        String motivo = JOptionPane.showInputDialog(this,
                "Ingrese motivo de rechazo:");

        if (motivo == null || motivo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un motivo");
            return;
        }

        if (dao.rechazar(id, motivo)) {
            JOptionPane.showMessageDialog(this, "Solicitud rechazada");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al rechazar");
        }
    }//GEN-LAST:event_btnRechazarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprovar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSolicitudes;
    // End of variables declaration//GEN-END:variables
}
