package vistas;

import dao.UsuarioDAO;
import modelo.Usuario;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class FrmUsuarios extends javax.swing.JInternalFrame {

    UsuarioDAO dao = new UsuarioDAO();
    
    public FrmUsuarios() {
        initComponents();
        cargarTabla();
        
        btnActualizar.setEnabled(false);
        btnActivar.setEnabled(false);
        btnDesactivar.setEnabled(false);
    }
    
    private void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
        modelo.setRowCount(0);

        List<Usuario> lista = dao.listarUsuarios();

        for (Usuario u : lista) {
            modelo.addRow(new Object[]{
                    u.getIdUsuario(),
                    u.getUsername(),
                    u.getNombreCompleto(),
                    u.getRol(),
                    u.isEstado() ? "ACTIVO" : "INACTIVO"
            });
        }
    }
    
    
    // LIMPIAR
    private void limpiar() {
        txtId.setText("");
        txtUserName.setText("");
        cmbRol.setSelectedIndex(2);

        btnActualizar.setEnabled(false);
        btnActivar.setEnabled(false);
        btnDesactivar.setEnabled(false);
        cmbRol.setEnabled(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        txtId = new javax.swing.JLabel();
        btnDesactivar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel11.setText("Username:");

        txtUserName.setEditable(false);
        txtUserName.setEnabled(false);

        jLabel12.setText("Tipo de usuario:");

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "ENCARGADO", "EMPLEADO" }));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setText("REGISTROS DE USUARIOS");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Usuario", "Nombre", "Rol", "Estado"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        txtId.setText("Id");
        txtId.setEnabled(false);

        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnDesactivar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActivar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtId)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDesactivar)
                        .addComponent(btnActivar)
                        .addComponent(btnLimpiar))
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {

            int id = Integer.parseInt(txtId.getText());
            String username = txtUserName.getText();

            if (username.equalsIgnoreCase("admin")) {
                JOptionPane.showMessageDialog(
                    this,
                    "El usuario maestro ADMIN no permite modificación de rol.",
                    "Acción bloqueada",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            String rol = cmbRol.getSelectedItem().toString();

            if (dao.actualizarRol(id, rol)) {
                JOptionPane.showMessageDialog(this, "Rol actualizado");
                cargarTabla();
                limpiar();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        int fila = tblUsuarios.getSelectedRow(); 
        if (fila == -1) return; 
        txtId.setText(tblUsuarios.getValueAt(fila, 0).toString());
        txtUserName.setText(tblUsuarios.getValueAt(fila, 1).toString()); 
        cmbRol.setSelectedItem(tblUsuarios.getValueAt(fila, 3).toString()); 
        String estado = tblUsuarios.getValueAt(fila, 4).toString(); 
        
        String username = txtUserName.getText();

        if (username.equalsIgnoreCase("admin")) {
            btnActualizar.setEnabled(false);
            btnDesactivar.setEnabled(false);
            btnActivar.setEnabled(false);
            cmbRol.setEnabled(false);
        } else {
            cmbRol.setEnabled(true);
            btnActualizar.setEnabled(true);

            if (estado.equals("ACTIVO")) {
                btnActivar.setEnabled(false);
                btnDesactivar.setEnabled(true);
            } else {
                btnActivar.setEnabled(true);
                btnDesactivar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        try {
            int id = Integer.parseInt(txtId.getText());
            String username = txtUserName.getText();

            if (username.equalsIgnoreCase("admin")) {
                JOptionPane.showMessageDialog(
                    this,
                    "El usuario maestro ADMIN no puede desactivarse.",
                    "Acción bloqueada",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this,
                "¿Desea desactivar este usuario?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                if (dao.desactivar(id)) {
                    JOptionPane.showMessageDialog(this, "Usuario desactivado");
                    cargarTabla();
                    limpiar();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario");
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        try {
            int id = Integer.parseInt(txtId.getText());

            int confirm = JOptionPane.showConfirmDialog(this,
                "¿Desea activar este usuario?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                if (dao.activar(id)) {
                    JOptionPane.showMessageDialog(this, "Usuario activado");
                    cargarTabla();
                    limpiar();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario");
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
