package vistas;

import dao.VehiculoDAO;
import modelo.Vehiculo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmVehiculos extends javax.swing.JInternalFrame {

    VehiculoDAO dao = new VehiculoDAO();
    
    /**
     * Creates new form FrmVehiculos
     */
    public FrmVehiculos() {
        initComponents();
        validarFormatoPlaca();
        cargarTabla();
        btnActualizar.setEnabled(false);
        btnInhabilitar.setEnabled(false);
        btnHabilitar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        Tipo = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        Tipo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdVehiculo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnInhabilitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnHabilitar = new javax.swing.JButton();
        txtPasajeros = new javax.swing.JFormattedTextField();
        txtPlaca = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Carga y consulta de vehiculos");

        jLabel1.setText("Marca: ");

        jLabel2.setText("Modelo: ");

        jLabel3.setText("Placa: ");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Sedan", "Camioneta", "Pickup" }));

        Tipo.setText("Tipo: ");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISPONIBLE", "MANTENIMIENTO", "INHABILITADO" }));

        Tipo1.setText("Estado: ");

        jLabel4.setText("Id: ");

        txtIdVehiculo.setEditable(false);
        txtIdVehiculo.setEnabled(false);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnInhabilitar.setText("Inhabilitar");
        btnInhabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInhabilitarActionPerformed(evt);
            }
        });

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Marca", "Modelo", "Placa", "Pasajeros", "Tipo", "Estado"
            }
        ));
        tblVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehiculos);

        jLabel5.setText("Buscar por Placa: ");

        jLabel6.setText("Máx. Pasajeros:");

        btnHabilitar.setText("Habilitar");
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });

        txtPasajeros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)
                                .addGap(33, 33, 33)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel4))
                                                .addGap(29, 29, 29))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtIdVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tipo)
                                    .addComponent(Tipo1)
                                    .addComponent(jLabel3))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInhabilitar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHabilitar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE)
                                .addComponent(cmbTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Tipo1)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Tipo)
                                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(44, 44, 44))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))))
                            .addGap(44, 44, 44))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnInhabilitar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnHabilitar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblVehiculos.getModel();
        modelo.setRowCount(0);

        for (Vehiculo v : dao.listar()) {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getMarca(),
                v.getModelo(),
                v.getPlaca(),
                v.getPasajeros(),
                v.getTipo(),
                v.getEstado()
            });
        }
    }
    
    public void limpiar() {
        txtIdVehiculo.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtPlaca.setText("P");
        txtPasajeros.setText("");
        txtBuscar.setText("");
        cmbTipo.setSelectedIndex(0);
        cmbEstado.setSelectedIndex(0);
        btnActualizar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnInhabilitar.setEnabled(false);
        btnHabilitar.setEnabled(false);
    }
    
    private void validarFormatoPlaca() {

        txtPlaca.setText("P");

        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {

            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {

                char c = Character.toUpperCase(evt.getKeyChar());

                if (c == '\b') {
                    return;
                }

                String texto = txtPlaca.getText();
                
                // solo HEX
                if (!Character.isDigit(c)
                        && !(c >= 'A' && c <= 'F')
                        && c != '\b') {

                    evt.consume();
                    return;
                }
                
                // impedir más de 7 caracteres visibles (PAAA-AAA)
                if (texto.length() >= 8) {
                    evt.consume();
                    return;
                }

                
            }

            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {

                String placa = txtPlaca.getText()
                        .toUpperCase()
                        .replace("-", "");

                // mantener P fija
                if (!placa.startsWith("P")) {
                    placa = "P";
                }

                // eliminar todo excepto letras y números
                placa = placa.replaceAll("[^PA-F0-9]", "");
                // máximo P + 6
                if (placa.length() > 7) {
                    placa = placa.substring(0, 7);
                }

                // insertar guion automático
                if (placa.length() > 4) {
                    placa =
                            placa.substring(0, 4)
                            + "-"
                            + placa.substring(4);
                }

                txtPlaca.setText(placa);

                // cursor al final
                txtPlaca.setCaretPosition(txtPlaca.getText().length());
            }
        });
    }
    
    private void gestionarBotones(String estado) {
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnInhabilitar.setEnabled(false);
        btnHabilitar.setEnabled(false);

        switch (estado) {
            case "INHABILITADO":
                btnHabilitar.setEnabled(true);
                break;

            case "DISPONIBLE":
            case "MANTENIMIENTO":
                btnActualizar.setEnabled(true);
                btnInhabilitar.setEnabled(true);
                break;
        }
    }
    
    public void validarCampos() throws Exception  {
        String marca = txtMarca.getText().trim();
        String modelo = txtModelo.getText().trim();
        String placa = txtPlaca.getText().trim();
        // CAMPOS VACÍOS
        if (marca.isEmpty() || modelo.isEmpty() || placa.isEmpty() 
                || txtPasajeros.getText().trim().isEmpty()) {
            throw new Exception("Todos los campos deben completarse.");
        }
        
        //validar formato placa
        if (!placa.matches("^P[A-F0-9]{3}-[A-F0-9]{3}$")) {
            throw new Exception("Formato inválido. Use: PXXX-XXX. Solo letras A-F y números 0-9.");
        }

        // Validar marca (solo letras)
        if (!marca.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            throw new Exception("La marca solo debe contener letras.");
        }

        // Validar modelo (puede tener letras y números)
        if (!modelo.matches("[a-zA-Z0-9\\- ]+")) {
            throw new Exception("El modelo solo debe contener letras, números y guiones.");
        }

        try {
            int pasajeros = Integer.parseInt(txtPasajeros.getText());
            
            if (pasajeros < 2 || pasajeros > 10) {
                throw new Exception(
                    "Un vehículo debe permitir mínimo 2 pasajeros, máximo 10."
                );
            }
        } catch (NumberFormatException e) {
            throw new Exception("La cantidad de pasajeros debe ser un número entero.");
        }
        
        String estado = cmbEstado.getSelectedItem().toString();
        
        if(cmbTipo.getSelectedIndex() == 0){
            throw new Exception("Debe seleccionar el tipo de vehículo.");
        }
        
        if (estado.equals("INHABILITADO")) {
            throw new Exception("Para inhabilitar use el botón correspondiente.");
        }
       
    }
           
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            validarCampos();
            String placa = txtPlaca.getText();
            if (dao.placaExiste(0, placa)) {
                throw new Exception("La placa ya está registrada.");
            }

            Vehiculo v = new Vehiculo();

            v.setMarca(txtMarca.getText());
            v.setModelo(txtModelo.getText());
            v.setPlaca(txtPlaca.getText().toUpperCase());
            v.setPasajeros(Integer.parseInt(txtPasajeros.getText()));
            v.setTipo(cmbTipo.getSelectedItem().toString());
            v.setEstado(cmbEstado.getSelectedItem().toString());
            
            if (dao.insertar(v)) {
                JOptionPane.showMessageDialog(this, "Guardado correctamente");
                cargarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnInhabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInhabilitarActionPerformed
        int fila = tblVehiculos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un vehículo");
            return;
        }

        String estado = tblVehiculos.getValueAt(fila, 6).toString();

        if (estado.equals("INHABILITADO")) {
            JOptionPane.showMessageDialog(this, "El vehículo ya está inhabilitado");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Desea inhabilitar este vehículo?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            int id = Integer.parseInt(tblVehiculos.getValueAt(fila, 0).toString());

            if (dao.inhabilitar(id)) {
                JOptionPane.showMessageDialog(this, "Vehículo inhabilitado correctamente");
                cargarTabla();
                limpiar();

                //resetear botones
                btnInhabilitar.setEnabled(false);
                btnHabilitar.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(this, "Error al inhabilitar");
            }
        }
    }//GEN-LAST:event_btnInhabilitarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            validarCampos();
            int id = Integer.parseInt(txtIdVehiculo.getText());
            
            String estadoActual = cmbEstado.getSelectedItem().toString();

            if (estadoActual.equals("INHABILITADO")) {
                JOptionPane.showMessageDialog(this, "No se puede modificar este vehículo en su estado actual.");
                return;
            }

            String placa = txtPlaca.getText().toUpperCase();

            if (dao.placaExiste(id, placa)) {
                throw new Exception("La placa ya pertenece a otro vehículo.");
            }
            
            Vehiculo v = new Vehiculo();

            v.setId(Integer.parseInt(txtIdVehiculo.getText()));
            v.setMarca(txtMarca.getText());
            v.setModelo(txtModelo.getText());
            v.setPlaca(txtPlaca.getText().toUpperCase());
            v.setPasajeros(Integer.parseInt(txtPasajeros.getText()));
            v.setTipo(cmbTipo.getSelectedItem().toString());
            v.setEstado(cmbEstado.getSelectedItem().toString());

            if (dao.actualizar(v)) {
                JOptionPane.showMessageDialog(this, "Actualizado correctamente");
                cargarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculosMouseClicked
        int fila = tblVehiculos.getSelectedRow();

        txtIdVehiculo.setText(tblVehiculos.getValueAt(fila, 0).toString());
        txtMarca.setText(tblVehiculos.getValueAt(fila, 1).toString());
        txtModelo.setText(tblVehiculos.getValueAt(fila, 2).toString());
        txtPlaca.setText(tblVehiculos.getValueAt(fila, 3).toString());
        txtPasajeros.setText(tblVehiculos.getValueAt(fila, 4).toString());
        cmbTipo.setSelectedItem(tblVehiculos.getValueAt(fila, 5).toString());

        String estado = tblVehiculos.getValueAt(fila, 6).toString();

        cmbEstado.setSelectedItem(estado);

        gestionarBotones(estado);
    }//GEN-LAST:event_tblVehiculosMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        int pos = txtBuscar.getCaretPosition();

        txtBuscar.setText(txtBuscar.getText().toUpperCase());
        txtBuscar.setCaretPosition(pos);

        String placa = txtBuscar.getText();

        DefaultTableModel modelo = (DefaultTableModel) tblVehiculos.getModel();
        modelo.setRowCount(0);

        if (placa.isEmpty()) {
            cargarTabla();
            return;
        }

        for (Vehiculo v : dao.buscarPorPlaca(placa)) {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getMarca(),
                v.getModelo(),
                v.getPlaca(),
                v.getPasajeros(),
                v.getTipo(),
                v.getEstado()
            });
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
         int fila = tblVehiculos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un vehículo");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Desea habilitar este vehículo?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            int id = Integer.parseInt(tblVehiculos.getValueAt(fila, 0).toString());

            if (dao.habilitar(id)) {
                JOptionPane.showMessageDialog(this, "Vehículo habilitado correctamente");
                cargarTabla();
                limpiar();

                //resetear botones
                btnInhabilitar.setEnabled(false);
                btnHabilitar.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(this, "Error al habilitar");
            }
        }
    }//GEN-LAST:event_btnHabilitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Tipo1;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JButton btnInhabilitar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdVehiculo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JFormattedTextField txtPasajeros;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
