package vistas;

import dao.VehiculoDAO;
import java.text.ParseException;
import javax.swing.DefaultComboBoxModel;
import modelo.Vehiculo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

public class FrmVehiculos extends javax.swing.JInternalFrame {

    VehiculoDAO dao = new VehiculoDAO();
    
    /**
     * Creates new form FrmVehiculos
     */
    public FrmVehiculos() {
        initComponents();
        cmbEstado.removeItem("ASIGNADO");
        cargarTabla();
        btnActualizar.setEnabled(false);
        btnInhabilitar.setEnabled(false);
        btnHabilitar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        Tipo = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        Tipo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdVehiculo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnInhabilitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPasajeros = new javax.swing.JTextField();
        btnHabilitar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Carga y consulta de vehiculos");

        jLabel1.setText("Marca: ");

        jLabel2.setText("Modelo: ");

        jLabel3.setText("Placa: ");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Sedan", "Camioneta", "Pickup", " " }));

        Tipo.setText("Tipo: ");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISPONIBLE", "ASIGNADO", "MANTENIMIENTO", "INHABILITADO" }));

        Tipo1.setText("Estado: ");

        jLabel4.setText("Id: ");

        txtIdVehiculo.setEditable(false);
        txtIdVehiculo.setEnabled(false);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnInhabilitar.setText("Inhabilitar");
        btnInhabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInhabilitarActionPerformed(evt);
            }
        });

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Marca", "Modelo", "Placa", "Pasajeros", "Tipo", "Estado"
            }
        ));
        tblVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehiculos);

        jLabel5.setText("Buscar por Placa: ");

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("PAAA-AAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaKeyReleased(evt);
            }
        });

        jLabel6.setText("Máx. Pasajeros:");

        btnHabilitar.setText("Habilitar");
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtIdVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tipo)
                                    .addComponent(Tipo1)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)
                                .addGap(33, 33, 33)
                                .addComponent(btnLimpiar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInhabilitar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHabilitar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(cmbEstado, 0, 140, Short.MAX_VALUE)
                                .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Tipo1)
                                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Tipo)
                                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))))
                                .addGap(44, 44, 44)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnInhabilitar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnHabilitar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblVehiculos.getModel();
        modelo.setRowCount(0);

        for (Vehiculo v : dao.listar()) {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getMarca(),
                v.getModelo(),
                v.getPlaca(),
                v.getPasajeros(),
                v.getTipo(),
                v.getEstado()
            });
        }
    }
    
    public void limpiar() {
        txtIdVehiculo.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtPlaca.setText("");
        txtPasajeros.setText("");
        txtBuscar.setText("");
        cmbTipo.setSelectedIndex(0);
        cmbEstado.setSelectedIndex(0);
        btnActualizar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnInhabilitar.setEnabled(false);
        btnHabilitar.setEnabled(false);
    }
    
    private void formatoPlaca() {
        try {
            MaskFormatter formatter = new MaskFormatter("PAAA AAA");
            formatter.setPlaceholderCharacter('_');
            txtPlaca.setFormatterFactory(new DefaultFormatterFactory(formatter));
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }
    
    private void gestionarBotones(String estado) {
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnInhabilitar.setEnabled(false);
        btnHabilitar.setEnabled(false);

        switch (estado) {
            case "INHABILITADO":
                btnHabilitar.setEnabled(true);
                break;

            case "ASIGNADO":
                // ninguno activo
                break;

            case "DISPONIBLE":
            case "MANTENIMIENTO":
                btnActualizar.setEnabled(true);
                btnInhabilitar.setEnabled(true);
                break;
        }
    }
    
    public void validarCampos() throws Exception  {
        String marca = txtMarca.getText().trim();
        String modelo = txtModelo.getText().trim();
        String placa = txtPlaca.getText().trim();
        // CAMPOS VACÍOS
        if (marca.isEmpty() || modelo.isEmpty() || placa.isEmpty()) {
            throw new Exception("Todos los campos deben completarse.");
        }

        // Validar marca (solo letras)
        if (!marca.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            throw new Exception("La marca solo debe contener letras.");
        }

        // Validar modelo (puede tener letras y números)
        if (!modelo.matches("[a-zA-Z0-9\\- ]+")) {
            throw new Exception("El modelo solo debe contener letras, números y guiones.");
        }
        
        String estado = cmbEstado.getSelectedItem().toString();
        
        if(cmbTipo.getSelectedIndex() == 0){
            throw new Exception("Debe seleccionar el tipo de vehículo.");
        }
        
        if (estado.equals("ASIGNADO")) {
            throw new Exception("No puedes asignar un vehículo desde aquí.");
        }

        if (estado.equals("INHABILITADO")) {
            throw new Exception("Para inhabilitar use el botón correspondiente.");
        }
       
    }
           
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            validarCampos();
            String placa = txtPlaca.getText();
            if (dao.placaExiste(0, placa)) {
                throw new Exception("La placa ya está registrada.");
            }

            Vehiculo v = new Vehiculo();

            v.setMarca(txtMarca.getText());
            v.setModelo(txtModelo.getText());
            v.setPlaca(txtPlaca.getText().toUpperCase());
            v.setPasajeros(Integer.parseInt(txtPasajeros.getText()));
            v.setTipo(cmbTipo.getSelectedItem().toString());
            v.setEstado(cmbEstado.getSelectedItem().toString());
            
            if (dao.insertar(v)) {
                JOptionPane.showMessageDialog(this, "Guardado correctamente");
                cargarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnInhabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInhabilitarActionPerformed
        int fila = tblVehiculos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un vehículo");
            return;
        }

        String estado = tblVehiculos.getValueAt(fila, 6).toString();

        if (estado.equals("ASIGNADO")) {
            JOptionPane.showMessageDialog(this, "No se puede inhabilitar un vehículo asignado");
            return;
        }

        if (estado.equals("INHABILITADO")) {
            JOptionPane.showMessageDialog(this, "El vehículo ya está inhabilitado");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Desea inhabilitar este vehículo?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            int id = Integer.parseInt(tblVehiculos.getValueAt(fila, 0).toString());

            if (dao.inhabilitar(id)) {
                JOptionPane.showMessageDialog(this, "Vehículo inhabilitado correctamente");
                cargarTabla();
                limpiar();

                //resetear botones
                btnInhabilitar.setEnabled(false);
                btnHabilitar.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(this, "Error al inhabilitar");
            }
        }
    }//GEN-LAST:event_btnInhabilitarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            validarCampos();
            int id = Integer.parseInt(txtIdVehiculo.getText());
            
            String estadoActual = cmbEstado.getSelectedItem().toString();

            if (estadoActual.equals("ASIGNADO") || estadoActual.equals("INHABILITADO")) {
                JOptionPane.showMessageDialog(this, "No se puede modificar este vehículo en su estado actual.");
                return;
            }

            String placa = txtPlaca.getText().toUpperCase();

            if (dao.placaExiste(id, placa)) {
                throw new Exception("La placa ya pertenece a otro vehículo.");
            }
            
            Vehiculo v = new Vehiculo();

            v.setId(Integer.parseInt(txtIdVehiculo.getText()));
            v.setMarca(txtMarca.getText());
            v.setModelo(txtModelo.getText());
            v.setPlaca(txtPlaca.getText().toUpperCase());
            v.setPasajeros(Integer.parseInt(txtPasajeros.getText()));
            v.setTipo(cmbTipo.getSelectedItem().toString());
            v.setEstado(cmbEstado.getSelectedItem().toString());

            if (dao.actualizar(v)) {
                JOptionPane.showMessageDialog(this, "Actualizado correctamente");
                cargarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculosMouseClicked
        int fila = tblVehiculos.getSelectedRow();

        txtIdVehiculo.setText(tblVehiculos.getValueAt(fila, 0).toString());
        txtMarca.setText(tblVehiculos.getValueAt(fila, 1).toString());
        txtModelo.setText(tblVehiculos.getValueAt(fila, 2).toString());
        txtPlaca.setText(tblVehiculos.getValueAt(fila, 3).toString());
        txtPasajeros.setText(tblVehiculos.getValueAt(fila, 4).toString());
        cmbTipo.setSelectedItem(tblVehiculos.getValueAt(fila, 5).toString());

        String estado = tblVehiculos.getValueAt(fila, 6).toString();

        if (((DefaultComboBoxModel) cmbEstado.getModel()).getIndexOf("ASIGNADO") == -1) {
            cmbEstado.addItem("ASIGNADO");
        }

        cmbEstado.setSelectedItem(estado);

        gestionarBotones(estado);
    }//GEN-LAST:event_tblVehiculosMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        int pos = txtBuscar.getCaretPosition();

        txtBuscar.setText(txtBuscar.getText().toUpperCase());
        txtBuscar.setCaretPosition(pos);

        String placa = txtBuscar.getText();

        DefaultTableModel modelo = (DefaultTableModel) tblVehiculos.getModel();
        modelo.setRowCount(0);

        if (placa.isEmpty()) {
            cargarTabla();
            return;
        }

        for (Vehiculo v : dao.buscarPorPlaca(placa)) {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getMarca(),
                v.getModelo(),
                v.getPlaca(),
                v.getPasajeros(),
                v.getTipo(),
                v.getEstado()
            });
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyReleased
        int pos = txtPlaca.getCaretPosition();
        txtPlaca.setText(txtPlaca.getText().toUpperCase());
        txtPlaca.setCaretPosition(pos);
    }//GEN-LAST:event_txtPlacaKeyReleased

    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
         int fila = tblVehiculos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un vehículo");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Desea habilitar este vehículo?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            int id = Integer.parseInt(tblVehiculos.getValueAt(fila, 0).toString());

            if (dao.habilitar(id)) {
                JOptionPane.showMessageDialog(this, "Vehículo habilitado correctamente");
                cargarTabla();
                limpiar();

                //resetear botones
                btnInhabilitar.setEnabled(false);
                btnHabilitar.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(this, "Error al habilitar");
            }
        }
    }//GEN-LAST:event_btnHabilitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Tipo1;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JButton btnInhabilitar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdVehiculo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPasajeros;
    private javax.swing.JFormattedTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
