package vistas;

import dao.EmpleadoDAO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;

public class FrmEmpleados extends javax.swing.JInternalFrame {
    EmpleadoDAO dao = new EmpleadoDAO();
    /**
     * Creates new form FrmEmpleados
     */
    public FrmEmpleados() {
        initComponents();
        cargarTabla();
        ButtonGroup grupoLicencia = new ButtonGroup();
        grupoLicencia.add(rbSiLicencia);
        grupoLicencia.add(rbNoLicencia);
        
        txtLicencia.setEnabled(false);
        rbNoLicencia.setSelected(true);
        txtLicencia.setText("SIN LICENCIA");
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDui = new javax.swing.JFormattedTextField();
        txtCargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        rbSiLicencia = new javax.swing.JRadioButton();
        rbNoLicencia = new javax.swing.JRadioButton();
        txtLicencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setText("REGISTROS DE EMPLEADOS");

        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Nombres:");

        jLabel2.setText("Apellidos:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("DUI:");

        try {
            txtDui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Cargo:");

        jLabel6.setText("Departamento:");

        jLabel8.setText("¿Posee Licencia?");

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Dui", "Telefono", "Cargo", "Departamento", "Estado", "Licencia", "Usuario"
            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        rbSiLicencia.setText("Si");
        rbSiLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSiLicenciaActionPerformed(evt);
            }
        });

        rbNoLicencia.setText("No");
        rbNoLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoLicenciaActionPerformed(evt);
            }
        });

        jLabel10.setText("Licencia:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtIdEmpleado.setEditable(false);
        txtIdEmpleado.setEnabled(false);

        jLabel11.setText("Id:");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(36, 36, 36)
                                .addComponent(txtLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(rbSiLicencia)
                                .addGap(18, 18, 18)
                                .addComponent(rbNoLicencia)))
                        .addGap(115, 115, 115)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(30, 30, 30)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesactivar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActivar)
                        .addGap(252, 252, 252))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(rbSiLicencia)
                            .addComponent(rbNoLicencia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnActualizar)
                            .addComponent(btnDesactivar)
                            .addComponent(btnActivar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblEmpleados.getModel();
        modelo.setRowCount(0);

        for (Empleado e : dao.listar()) {
            modelo.addRow(new Object[]{
                e.getIdEmpleado(),
                e.getNombres(),
                e.getApellidos(),
                e.getDui(),
                e.getTelefono(),
                e.getCargo(),
                e.getDepartamento(),
                e.getEstado(),
                e.getLicencia(),
                e.getUsername()
            });
        }
    }
    
    private void validarCampos() throws Exception {
        if (txtNombres.getText().trim().isEmpty() ||
            txtApellidos.getText().trim().isEmpty() ||
            txtCargo.getText().trim().isEmpty() ||
            txtDepartamento.getText().trim().isEmpty()) {

            throw new Exception("Todos los campos deben completarse.");
        }

        if (txtDui.getText().contains("_")) {
            throw new Exception("Complete el DUI.");
        }

        if (txtTelefono.getText().contains("_")) {
            throw new Exception("Complete el teléfono.");
        }
    }
    
    public void limpiar() {
        txtIdEmpleado.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCargo.setText("");
        txtDepartamento.setText("");
        txtDui.setText("");
        txtTelefono.setText("");
        txtLicencia.setText("");

        rbNoLicencia.setSelected(true);
        txtLicencia.setEnabled(false);
        
        btnActivar.setEnabled(false);
        btnDesactivar.setEnabled(false);
        btnActualizar.setEnabled(false);
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        try {
            validarCampos();

            String dui = txtDui.getText();

            if (dao.duiExiste(0, dui)) {
                throw new Exception("DUI ya existe.");
            }
            
            String licencia;
            if (rbSiLicencia.isSelected()) {
                licencia = txtLicencia.getText().trim();

                if (licencia.isEmpty()) {
                    throw new Exception("Debe ingresar el número de licencia.");
                }
            } else {
                licencia = "SIN LICENCIA";
            } 

            Empleado e = new Empleado();

            e.setNombres(txtNombres.getText());
            e.setApellidos(txtApellidos.getText());
            e.setDui(dui);
            e.setTelefono(txtTelefono.getText());
            e.setCargo(txtCargo.getText());
            e.setDepartamento(txtDepartamento.getText());
            e.setLicencia(licencia);

            if (dao.insertar(e)) {
                JOptionPane.showMessageDialog(this, "Guardado");
                cargarTabla();
                limpiar();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        int fila = tblEmpleados.getSelectedRow();

        if (fila == -1) return;

        txtIdEmpleado.setText(tblEmpleados.getValueAt(fila, 0).toString());
        txtNombres.setText(tblEmpleados.getValueAt(fila, 1).toString());
        txtApellidos.setText(tblEmpleados.getValueAt(fila, 2).toString());
        txtDui.setText(tblEmpleados.getValueAt(fila, 3).toString());
        txtTelefono.setText(tblEmpleados.getValueAt(fila, 4).toString());
        txtCargo.setText(tblEmpleados.getValueAt(fila, 5).toString());
        txtDepartamento.setText(tblEmpleados.getValueAt(fila, 6).toString());

        String estado = tblEmpleados.getValueAt(fila, 7).toString();

        // Control de botones
        if ("ACTIVO".equals(estado)) {
            btnActivar.setEnabled(false);
            btnDesactivar.setEnabled(true);
        } else {
            btnActivar.setEnabled(true);
            btnDesactivar.setEnabled(false);
        }

        String lic = tblEmpleados.getValueAt(fila, 8).toString();

        // Licencia
        if ("SIN LICENCIA".equals(lic)) {
            rbNoLicencia.setSelected(true);
            txtLicencia.setEnabled(false);
            txtLicencia.setText("SIN LICENCIA");
        } else {
            rbSiLicencia.setSelected(true);
            txtLicencia.setEnabled(true);
            txtLicencia.setText(lic);
        }

        btnActualizar.setEnabled(true);
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            validarCampos();

            int id = Integer.parseInt(txtIdEmpleado.getText());
            String dui = txtDui.getText();

            if (dao.duiExiste(id, dui)) {
                throw new Exception("DUI ya existe.");
            }

            String licencia;
            if (rbSiLicencia.isSelected()) {
                licencia = txtLicencia.getText().trim();

                if (licencia.isEmpty()) {
                    throw new Exception("Debe ingresar el número de licencia.");
                }
            } else {
                licencia = "SIN LICENCIA";
            }

            Empleado e = new Empleado();

            e.setIdEmpleado(id);
            e.setNombres(txtNombres.getText());
            e.setApellidos(txtApellidos.getText());
            e.setDui(dui);
            e.setTelefono(txtTelefono.getText());
            e.setCargo(txtCargo.getText());
            e.setDepartamento(txtDepartamento.getText());
            e.setLicencia(licencia);

            if (dao.actualizar(e)) {
                JOptionPane.showMessageDialog(this, "Actualizado correctamente");
                cargarTabla();
                limpiar();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void rbSiLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSiLicenciaActionPerformed
        txtLicencia.setEnabled(true);
        txtLicencia.setText("");
    }//GEN-LAST:event_rbSiLicenciaActionPerformed

    private void rbNoLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoLicenciaActionPerformed
        txtLicencia.setEnabled(false);
        txtLicencia.setText("SIN LICENCIA");
    }//GEN-LAST:event_rbNoLicenciaActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
       try {
            int id = Integer.parseInt(txtIdEmpleado.getText());

            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Desea desactivar este empleado?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                if (dao.desactivar(id)) {
                    JOptionPane.showMessageDialog(this, "Empleado desactivado");
                    cargarTabla();
                    limpiar();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado");
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
       try {
            int id = Integer.parseInt(txtIdEmpleado.getText());

            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Desea activar este empleado?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                if (dao.activar(id)) {
                    JOptionPane.showMessageDialog(this, "Empleado activado");
                    cargarTabla();
                    limpiar();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado");
        } 
    }//GEN-LAST:event_btnActivarActionPerformed

    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbNoLicencia;
    private javax.swing.JRadioButton rbSiLicencia;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JFormattedTextField txtDui;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
